# Generated by Django 2.2.1 on 2019-05-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=50, verbose_name='用户名称')),
                ('password', models.CharField(default='', help_text='名称', max_length=50, verbose_name='密码')),
                ('salt', models.CharField(default='', max_length=10, verbose_name='盐值')),
                ('type', models.IntegerField(default=0, help_text='0:普通用户，1：管理员', max_length=3, verbose_name='类型')),
                ('create_time', models.BigIntegerField(default=0, max_length=20, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
