# Generated by Django 2.2.1 on 2019-05-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0003_auto_20190508_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='名称', max_length=50, verbose_name='文章分类名称')),
                ('parent_id', models.IntegerField(default=0, help_text='0:普通用户，1：管理员', verbose_name='上级id')),
                ('path', models.CharField(default='', help_text='-0-', max_length=50, verbose_name='分类路径')),
                ('create_time', models.BigIntegerField(default=0, verbose_name='创建时间')),
                ('update_time', models.BigIntegerField(default=0, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '文章分类名称',
                'verbose_name_plural': '文章分类名称',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='文章标题')),
                ('summary', models.TextField(default='文章摘要等同于网页description内容，请务必填写...', max_length=230, verbose_name='文章摘要')),
                ('body', models.TextField(verbose_name='文章内容')),
                ('create_time', models.BigIntegerField(default=0, verbose_name='创建时间')),
                ('update_time', models.BigIntegerField(default=0, verbose_name='修改时间')),
                ('views', models.IntegerField(default=0, verbose_name='阅览量')),
                ('loves', models.IntegerField(default=0, verbose_name='喜爱量')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sf.User', verbose_name='作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sf.ArticleCategory', verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-create_time'],
            },
        ),
    ]
