# Generated by Django 2.2.1 on 2019-05-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0004_article_articlecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=230, verbose_name='评论内容')),
                ('create_time', models.BigIntegerField(default=0, verbose_name='创建时间')),
                ('update_time', models.BigIntegerField(default=0, verbose_name='修改时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sf.User', verbose_name='评论人')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-create_time'],
            },
        ),
    ]
