# Generated by Django 2.2.1 on 2019-05-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0006_auto_20190519_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_delete',
            field=models.IntegerField(default=0, help_text='0:没有，1：删除', verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_public',
            field=models.IntegerField(default=0, help_text='0:不是，1：是', verbose_name='是否私有'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_verify',
            field=models.IntegerField(default=0, help_text='0:未审核，1：通过，-1：不通过', verbose_name='是否审核过'),
        ),
    ]
