# Generated by Django 2.2.1 on 2019-05-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0007_auto_20190519_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.CharField(default='', max_length=150, verbose_name='文章图片'),
        ),
    ]
